name: LinkGrabber

on:
  schedule:
    - cron: '*/60 * * * *'
  pull_request_target:
    branches: [ main ]
  workflow_dispatch:

jobs:
  runCode:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN || github.token }}

      - name: Grab Link
        run: |
          git config --global user.email "fbk@hll.localhost"
          git config --global user.name "fbk"
          chmod +x exec_grabber.sh && ./exec_grabber.sh
          git add -A
          git commit -m "./youtubeLink.txt is updated." || echo "No changes to commit"
          git push --force origin main
